name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message)[0] }}
        run: echo "$COMMIT_MESSAGES"
      - name: contains test
        env:
          CONTAINS_TEST: ${{ contains(toJson(github.event.commits.*.message), 'Test' ) }}
        run: echo "$CONTAINS_TEST"
      - name: contains yes
        env:
          CONTAINS_YES: ${{ contains(toJson(github.event.commits.*.message), 'Yes' ) }}
        run: echo "$CONTAINS_YES"
      - name: contains skip
        env:
          CONTAINS_SKIP: ${{ contains(toJson(github.event.commits.*.message), 'Skip' ) }}
        run: echo "$CONTAINS_SKIP"
